/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uk.ac.bolton.view;

import java.awt.Color;
import uk.ac.bolton.services.impl.BehavioursImpl;
import uk.ac.bolton.service.Behaviours;

/**
 *
 * @author sachi
 */
public class ProfileForm extends javax.swing.JFrame {

    private final Behaviours channelBehaviours;
    private String userName;
    
    {
        channelBehaviours = new BehavioursImpl();
    }
    
    
    /**
     * Creates new form ProfileForm
     */
    public ProfileForm() {
        initComponents();
    }

    public ProfileForm(String userName) {
        this();
        this.userName = userName;
        setTitle(userName + "'s Timeline");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaTimeLine = new javax.swing.JTextArea();
        cmbChannels = new javax.swing.JComboBox<>();
        btnSubUnSub = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaTimeLine.setColumns(20);
        txtAreaTimeLine.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtAreaTimeLine.setRows(5);
        txtAreaTimeLine.setAlignmentX(1.0F);
        txtAreaTimeLine.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(txtAreaTimeLine);

        cmbChannels.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        cmbChannels.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABC Channel", "None" }));

        btnSubUnSub.setBackground(new java.awt.Color(204, 204, 0));
        btnSubUnSub.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnSubUnSub.setForeground(new java.awt.Color(255, 255, 255));
        btnSubUnSub.setText("Subscribe");
        btnSubUnSub.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubUnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubUnSubActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("News Feed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbChannels, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubUnSub, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbChannels)
                    .addComponent(btnSubUnSub, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubUnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubUnSubActionPerformed
        String buttonName = evt.getActionCommand();

        if(buttonName.equals("Subscribe")) {
            btnSubUnSub.setText("Unsubscribe");
            btnSubUnSub.setBackground(Color.DARK_GRAY);

            channelBehaviours.addSubscribers(userName, this);

        } else {
            btnSubUnSub.setText("Subscribe");
            btnSubUnSub.setBackground(new Color(255,102,102));

            channelBehaviours.removeSubscribers(userName);
        }
    }//GEN-LAST:event_btnSubUnSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileForm().setVisible(true);
            }
        });
    }
    
    
    
        /**
     * @return the txtAreaTimeLine
     */
    public javax.swing.JTextArea getTxtAreaTimeLine() {
        return txtAreaTimeLine;
    }

    /**
     * @return the cmbChannels
     */
    public javax.swing.JComboBox<String> getCmbChannels() {
        return cmbChannels;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubUnSub;
    private javax.swing.JComboBox<String> cmbChannels;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaTimeLine;
    // End of variables declaration//GEN-END:variables
}
